// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package pbDemo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustomerRequert struct {
	Id                   int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string                     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                     `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Addresses            []*CustomerRequert_Address `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CustomerRequert) Reset()         { *m = CustomerRequert{} }
func (m *CustomerRequert) String() string { return proto.CompactTextString(m) }
func (*CustomerRequert) ProtoMessage()    {}
func (*CustomerRequert) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}

func (m *CustomerRequert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequert.Unmarshal(m, b)
}
func (m *CustomerRequert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequert.Marshal(b, m, deterministic)
}
func (m *CustomerRequert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequert.Merge(m, src)
}
func (m *CustomerRequert) XXX_Size() int {
	return xxx_messageInfo_CustomerRequert.Size(m)
}
func (m *CustomerRequert) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequert.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequert proto.InternalMessageInfo

func (m *CustomerRequert) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerRequert) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomerRequert) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRequert) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRequert) GetAddresses() []*CustomerRequert_Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CustomerRequert_Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	IsShippingAddress    bool     `protobuf:"varint,5,opt,name=isShippingAddress,proto3" json:"isShippingAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerRequert_Address) Reset()         { *m = CustomerRequert_Address{} }
func (m *CustomerRequert_Address) String() string { return proto.CompactTextString(m) }
func (*CustomerRequert_Address) ProtoMessage()    {}
func (*CustomerRequert_Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0, 0}
}

func (m *CustomerRequert_Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerRequert_Address.Unmarshal(m, b)
}
func (m *CustomerRequert_Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerRequert_Address.Marshal(b, m, deterministic)
}
func (m *CustomerRequert_Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerRequert_Address.Merge(m, src)
}
func (m *CustomerRequert_Address) XXX_Size() int {
	return xxx_messageInfo_CustomerRequert_Address.Size(m)
}
func (m *CustomerRequert_Address) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerRequert_Address.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerRequert_Address proto.InternalMessageInfo

func (m *CustomerRequert_Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CustomerRequert_Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CustomerRequert_Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CustomerRequert_Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *CustomerRequert_Address) GetIsShippingAddress() bool {
	if m != nil {
		return m.IsShippingAddress
	}
	return false
}

type CustomerResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerResponse) Reset()         { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()    {}
func (*CustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}

func (m *CustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerResponse.Unmarshal(m, b)
}
func (m *CustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerResponse.Marshal(b, m, deterministic)
}
func (m *CustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerResponse.Merge(m, src)
}
func (m *CustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerResponse.Size(m)
}
func (m *CustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerResponse proto.InternalMessageInfo

func (m *CustomerResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CustomerFilter struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerFilter) Reset()         { *m = CustomerFilter{} }
func (m *CustomerFilter) String() string { return proto.CompactTextString(m) }
func (*CustomerFilter) ProtoMessage()    {}
func (*CustomerFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{2}
}

func (m *CustomerFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerFilter.Unmarshal(m, b)
}
func (m *CustomerFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerFilter.Marshal(b, m, deterministic)
}
func (m *CustomerFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerFilter.Merge(m, src)
}
func (m *CustomerFilter) XXX_Size() int {
	return xxx_messageInfo_CustomerFilter.Size(m)
}
func (m *CustomerFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerFilter.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerFilter proto.InternalMessageInfo

func (m *CustomerFilter) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerRequert)(nil), "pbDemo.CustomerRequert")
	proto.RegisterType((*CustomerRequert_Address)(nil), "pbDemo.CustomerRequert.Address")
	proto.RegisterType((*CustomerResponse)(nil), "pbDemo.CustomerResponse")
	proto.RegisterType((*CustomerFilter)(nil), "pbDemo.CustomerFilter")
}

func init() {
	proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46)
}

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0xbb, 0x76, 0xeb, 0x11, 0xea, 0x0c, 0x22, 0xc1, 0x1b, 0x4b, 0xaf, 0x8a, 0x48,
	0x2f, 0xe6, 0xad, 0x5e, 0x88, 0xe2, 0x03, 0xc4, 0x27, 0xe8, 0xda, 0x83, 0x0b, 0xae, 0x4d, 0x4c,
	0x52, 0x64, 0xbe, 0x82, 0xef, 0xe2, 0x33, 0x4a, 0xd2, 0x84, 0x81, 0xbb, 0x3b, 0xdf, 0x77, 0xfe,
	0x7c, 0xbf, 0x36, 0x50, 0x74, 0x93, 0x36, 0x62, 0x40, 0xd5, 0x48, 0x25, 0x8c, 0x20, 0x99, 0xdc,
	0xbe, 0xe0, 0x20, 0xaa, 0xdf, 0x18, 0xce, 0x9f, 0x7d, 0x8b, 0xe1, 0xe7, 0x84, 0xca, 0x90, 0x02,
	0x62, 0xde, 0xd3, 0xa8, 0x8c, 0xea, 0x94, 0xc5, 0xbc, 0x27, 0x04, 0x16, 0x63, 0x3b, 0x20, 0x8d,
	0xcb, 0xa8, 0xce, 0x99, 0xab, 0xc9, 0x25, 0xa4, 0x38, 0xb4, 0x7c, 0x4f, 0x13, 0x67, 0xce, 0xc2,
	0xba, 0x72, 0x27, 0x46, 0xa4, 0x8b, 0xd9, 0x75, 0x82, 0x3c, 0x42, 0xde, 0xf6, 0xbd, 0x42, 0xad,
	0x51, 0xd3, 0xb4, 0x4c, 0xea, 0xb3, 0xcd, 0x4d, 0x33, 0xe7, 0x37, 0xff, 0xb2, 0x9b, 0xa7, 0x79,
	0x90, 0x1d, 0x37, 0xae, 0x7f, 0x22, 0x58, 0x7a, 0x9b, 0x5c, 0x41, 0xa6, 0x8d, 0x42, 0x34, 0x0e,
	0x2f, 0x67, 0x5e, 0x59, 0xc4, 0x8e, 0x9b, 0x43, 0x40, 0xb4, 0xb5, 0x85, 0xd1, 0xa6, 0x35, 0x18,
	0x10, 0x9d, 0x20, 0x6b, 0x48, 0xbe, 0xb9, 0xf4, 0x80, 0xb6, 0x24, 0x77, 0x70, 0xc1, 0xf5, 0xdb,
	0x8e, 0x4b, 0xc9, 0xc7, 0x77, 0x1f, 0x44, 0xd3, 0x32, 0xaa, 0x57, 0xec, 0xb4, 0x51, 0x3d, 0xc0,
	0xfa, 0xc8, 0xac, 0xa5, 0x18, 0x35, 0x9e, 0xfc, 0x30, 0x0a, 0x4b, 0x3d, 0x75, 0x9d, 0xbd, 0x13,
	0xbb, 0x3b, 0x41, 0x56, 0xb7, 0x50, 0x84, 0xed, 0x57, 0xbe, 0x37, 0xa8, 0xec, 0xec, 0x07, 0x1e,
	0xbe, 0x84, 0xea, 0xfd, 0x27, 0x05, 0xb9, 0x01, 0x58, 0x85, 0xd9, 0x6d, 0xe6, 0x5e, 0xed, 0xfe,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xaa, 0x8d, 0xcf, 0xc7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
}

type customerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerClient(cc grpc.ClientConnInterface) CustomerClient {
	return &customerClient{cc}
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
}

// UnimplementedCustomerServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbDemo.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "customer.proto",
}
